[versions]
agp = "7.2.1" # see https://developer.android.com/studio/releases/gradle-plugin
kotlin = "1.7.0" # see https://developer.android.com/jetpack/androidx/releases/compose-kotlin
coroutines = "1.6.3"

accompanist = "0.24.13-rc"
compose-ui = "1.2.0-rc03"

[plugins]

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }

androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0-rc01" }

androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version = "1.1.4-alpha07" }

compose-activity = { module = "androidx.activity:activity-compose", version = "1.6.0-alpha05" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" } # Tooling support (Previews, etc.)

gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.42.0" }
google-material = { module = "com.google.android.material:material", version = "1.7.0-alpha02" }

junit-bom = { module = "org.junit:junit-bom", version = "5.9.0-RC1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

reorderable-compose = { module = "org.burnoutcrew.composereorderable:reorderable", version = "0.9.2" }













