[versions]
agp = "7.3.1" # see https://developer.android.com/studio/releases/gradle-plugin
kotlin = "1.7.20" # see https://developer.android.com/jetpack/androidx/releases/compose-kotlin
kotlinxCoroutines = "1.6.4"

accompanist = "0.28.0"
androidxActivityCompose = "1.6.1"
androidxComposeCompiler = "1.3.2"
androidxComposeMaterial = "1.3.1"
androidxComposeUi = "1.3.1"
androidxHilt = "1.0.0"
androidxNavigation = "2.5.3"
androidxSplashScreen = "1.0.0"
androidxTestJunit = "1.1.4"
coil = "2.2.2"
flippable = "1.0.6"
googleMaterial = "1.7.0"
hilt = "2.44.2"
junitBom = "5.9.1"
reorderableCompose = "0.9.6"
versionsGradlePlugin = "0.44.0"

[plugins]

[libraries]
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashScreen" }

androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestJunit" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidxComposeMaterial" } # Material design icons (extended)
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxComposeUi" }

flippable = { module = "com.wajahatkarim:flippable", version.ref = "flippable" } # https://devlibrary.withgoogle.com/products/android/repos/wajahatkarim3-Flippable

google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-gradlePluginClasspath = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" } # https://github.com/material-components/material-components-android/releases
gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsGradlePlugin" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

reorderable-compose = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderableCompose" }