[versions]
agp = "7.3.0" # see https://developer.android.com/studio/releases/gradle-plugin
kotlin = "1.7.20" # see https://developer.android.com/jetpack/androidx/releases/compose-kotlin
coroutines = "1.6.4"

accompanist = "0.26.5-rc"
compose-compiler = "1.3.2"
compose-ui = "1.3.0-rc01"
hilt = "2.44"
navigation = "2.5.2"

[plugins]

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0" }

androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version = "1.1.4-beta01" }

compose-activity = { module = "androidx.activity:activity-compose", version = "1.6.0-rc02" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" } # Tooling support (Previews, etc.)

flippable = { module = "com.wajahatkarim:flippable", version = "1.0.6" } # https://devlibrary.withgoogle.com/products/android/repos/wajahatkarim3-Flippable

google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-gradlePluginClasspath = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-material = { module = "com.google.android.material:material", version = "1.8.0-alpha01" } # https://github.com/material-components/material-components-android/releases
gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.43.0" }

junit-bom = { module = "org.junit:junit-bom", version = "5.9.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

reorderable-compose = { module = "org.burnoutcrew.composereorderable:reorderable", version = "0.9.2" }